// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"database/sql"
	"github.com/hamanako-palpal/cooler-cam-api/src/go/main/handle"
	"github.com/hamanako-palpal/cooler-cam-api/src/go/main/infra"
	"github.com/hamanako-palpal/cooler-cam-api/src/go/main/services"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func Initialize(db *sql.DB) (*handle.HandlerGen, error) {
	smplHandler := handle.InitSmplHandler()
	visionRepository := infra.InitVisionCli()
	labelRepository := infra.InitLabelCli(db)
	camService := services.NewCamService(visionRepository, labelRepository)
	camHandler := handle.InitCamHandler(camService)
	handlerGen := handle.InitHandlerGen(smplHandler, camHandler)
	return handlerGen, nil
}
