# ベースとなるDockerイメージ指定
FROM golang:latest

ENV GO111MODULE=on
ENV EXEC_ENV=product
# コンテナ内に作業ディレクトリを作成
RUN mkdir /go/src/work
# コンテナログイン時のディレクトリ指定
WORKDIR /go/src/work
# ホストのファイルをコンテナの作業ディレクトリに移行
ADD . /go/src/work

RUN go build -o=/build/app
RUN chmod u+x /build/app

ENTRYPOINT ["/build/app"]